"""empty message

Revision ID: 2c5e8e3b71ab
Revises: c76207f6dcd2
Create Date: 2020-05-25 18:48:29.233131

"""
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5e8e3b71ab'
down_revision = 'c76207f6dcd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
#    op.create_table('geography_columns',
#    sa.Column('f_table_catalog', sa.String(), nullable=True),
#    sa.Column('f_table_schema', sa.String(), nullable=True),
#    sa.Column('f_table_name', sa.String(), nullable=True),
#    sa.Column('f_geography_column', sa.String(), nullable=True),
#    sa.Column('coord_dimension', sa.Integer(), nullable=True),
#    sa.Column('srid', sa.Integer(), nullable=True),
#    sa.Column('type', sa.Text(), nullable=True)
#    )
#    op.create_table('geometry_columns',
#    sa.Column('f_table_catalog', sa.String(length=256), nullable=True),
#    sa.Column('f_table_schema', sa.String(), nullable=True),
#    sa.Column('f_table_name', sa.String(), nullable=True),
#    sa.Column('f_geometry_column', sa.String(), nullable=True),
#    sa.Column('coord_dimension', sa.Integer(), nullable=True),
#    sa.Column('srid', sa.Integer(), nullable=True),
#    sa.Column('type', sa.String(length=30), nullable=True)
#    )
#    op.create_table('raster_columns',
#    sa.Column('r_table_catalog', sa.String(), nullable=True),
#    sa.Column('r_table_schema', sa.String(), nullable=True),
#    sa.Column('r_table_name', sa.String(), nullable=True),
#    sa.Column('r_raster_column', sa.String(), nullable=True),
#    sa.Column('srid', sa.Integer(), nullable=True),
#    sa.Column('scale_x', sa.Float(precision=53), nullable=True),
#    sa.Column('scale_y', sa.Float(precision=53), nullable=True),
#    sa.Column('blocksize_x', sa.Integer(), nullable=True),
#    sa.Column('blocksize_y', sa.Integer(), nullable=True),
#    sa.Column('same_alignment', sa.Boolean(), nullable=True),
#    sa.Column('regular_blocking', sa.Boolean(), nullable=True),
#    sa.Column('num_bands', sa.Integer(), nullable=True),
#    sa.Column('pixel_types', sa.ARRAY(sa.TEXT()), nullable=True),
#    sa.Column('nodata_values', sa.ARRAY(sa.Float(precision=53)), nullable=True),
#    sa.Column('out_db', sa.Boolean(), nullable=True),
#    sa.Column('extent', geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
#    sa.Column('spatial_index', sa.Boolean(), nullable=True)
#    )
#    op.create_table('raster_overviews',
#    sa.Column('o_table_catalog', sa.String(), nullable=True),
#    sa.Column('o_table_schema', sa.String(), nullable=True),
#    sa.Column('o_table_name', sa.String(), nullable=True),
#    sa.Column('o_raster_column', sa.String(), nullable=True),
#    sa.Column('r_table_catalog', sa.String(), nullable=True),
#    sa.Column('r_table_schema', sa.String(), nullable=True),
#    sa.Column('r_table_name', sa.String(), nullable=True),
#    sa.Column('r_raster_column', sa.String(), nullable=True),
#    sa.Column('overview_factor', sa.Integer(), nullable=True)
#    )
#    op.create_index(op.f('ix_All_Strava_Activities_geom'), 'All_Strava_Activities', ['geom'], unique=False)
#    op.drop_index('sidx_All_Strava_Activities_geom', table_name='All_Strava_Activities')
#    op.create_index(op.f('ix_CA_Counties_geom'), 'CA_Counties', ['geom'], unique=False)
#    op.drop_index('sidx_CA_Counties_geom', table_name='CA_Counties')
#    op.create_index(op.f('ix_California_Places_geom'), 'California_Places', ['geom'], unique=False)
#    op.drop_index('sidx_California_Places_geom', table_name='California_Places')
#    op.create_index(op.f('ix_OSM_Central_CA_Trails_geom'), 'OSM_Central_CA_Trails', ['geom'], unique=False)
#    op.drop_index('sidx_OSM_Central_CA_Trails_geom', table_name='OSM_Central_CA_Trails')
#    op.create_index(op.f('ix_POI_geom'), 'POI', ['geom'], unique=False)
#    op.drop_index('sidx_POI_geom', table_name='POI')
    op.add_column('gpsapidattest', sa.Column('POI', sa.String(length=30), nullable=True))
    op.add_column('gpsapidattest', sa.Column('city', sa.String(length=30), nullable=True))
    op.add_column('gpsapidattest', sa.Column('county', sa.String(length=30), nullable=True))
    op.add_column('gpsapidattest', sa.Column('dist_nearestroad', sa.Float(), nullable=True))
    op.add_column('gpsapidattest', sa.Column('dist_nearesttrail', sa.Float(), nullable=True))
    op.add_column('gpsapidattest', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('gpsapidattest', sa.Column('nearestroad', sa.String(length=30), nullable=True))
    op.add_column('gpsapidattest', sa.Column('nearesttrail', sa.String(length=30), nullable=True))
#    op.create_index(op.f('ix_moco_roads_geom'), 'moco_roads', ['geom'], unique=False)
#    op.drop_index('sidx_moco_roads_geom', table_name='moco_roads')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
#    op.create_index('sidx_moco_roads_geom', 'moco_roads', ['geom'], unique=False)
#    op.drop_index(op.f('ix_moco_roads_geom'), table_name='moco_roads')
    op.drop_column('gpsapidattest', 'nearesttrail')
    op.drop_column('gpsapidattest', 'nearestroad')
    op.drop_column('gpsapidattest', 'geom')
    op.drop_column('gpsapidattest', 'dist_nearesttrail')
    op.drop_column('gpsapidattest', 'dist_nearestroad')
    op.drop_column('gpsapidattest', 'county')
    op.drop_column('gpsapidattest', 'city')
    op.drop_column('gpsapidattest', 'POI')
#    op.create_index('sidx_POI_geom', 'POI', ['geom'], unique=False)
#    op.drop_index(op.f('ix_POI_geom'), table_name='POI')
#    op.create_index('sidx_OSM_Central_CA_Trails_geom', 'OSM_Central_CA_Trails', ['geom'], unique=False)
#    op.drop_index(op.f('ix_OSM_Central_CA_Trails_geom'), table_name='OSM_Central_CA_Trails')
#    op.create_index('sidx_California_Places_geom', 'California_Places', ['geom'], unique=False)
#    op.drop_index(op.f('ix_California_Places_geom'), table_name='California_Places')
#    op.create_index('sidx_CA_Counties_geom', 'CA_Counties', ['geom'], unique=False)
#    op.drop_index(op.f('ix_CA_Counties_geom'), table_name='CA_Counties')
#    op.create_index('sidx_All_Strava_Activities_geom', 'All_Strava_Activities', ['geom'], unique=False)
#    op.drop_index(op.f('ix_All_Strava_Activities_geom'), table_name='All_Strava_Activities')
#    op.drop_table('raster_overviews')
#    op.drop_table('raster_columns')
#    op.drop_table('geometry_columns')
#    op.drop_table('geography_columns')
    # ### end Alembic commands ###
